Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "private_network", ip: "192.168.56.2"#, virtualbox__intnet:true
  config.vm.network "forwarded_port", guest: 3306, host: 1233
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 80, host: 1232
  config.vm.provision "shell", path: "setup.sh" 

end